cabal-version: 2.4
name: nesycat-hasktorch
version: 0.1.0.0
synopsis: NeSyCat Framework with HaskTorch
description: Typed tensor category for the NeSyCat neurosymbolic framework
license: MIT
author: User
maintainer: user@example.com

library
  exposed-modules:
    -- Alpha: Categorical
    A_Categorical.CategoricalSignature,
    A_Categorical.CategoricalInterpretation,
    A_Categorical.Category.Categories.Data,
    A_Categorical.Category.Categories.Tens,
    A_Categorical.Category.Monads.Dist,
    A_Categorical.Category.Monads.Giry,
    A_Categorical.Category.Monads.DistExpect,
    A_Categorical.Category.Monads.GiryExpect,
    -- Beta: Logical
    B_Logical.LogicalSignature,
    B_Logical.LogicalQuantSignature,
    B_Logical.Interpretations.Boolean,
    B_Logical.Interpretations.Tensor,
    -- Gamma: Domain
    C_Domain.Examples.Binary.Signature,
    C_Domain.Examples.Binary.Interpretation,
    C_Domain.Models.MLP,
    -- Delta: Grammatical
    D_Grammatical.Examples.Binary.Formulas,
    D_Grammatical.Examples.Binary.IntpTens,
    D_Grammatical.Examples.Binary.IntpData,
    -- Epsilon: Inferential
    E_Inferential.InferenceSignature,
    E_Inferential.InferenceInterpretation,
    E_Inferential.Library.Softplus,
    E_Inferential.Library.OneMinus,
    E_Inferential.Library.NegLog,
    E_Inferential.Library.CrossEntropy,
    E_Inferential.Library.Convex,
    -- Zeta: Statistical
    F_Statistical.B_Theory.BenchmarkTheory,
    F_Statistical.D_Vocabulary.BenchmarkVocab,
    F_Statistical.DA_Realization.BenchmarkRlzData,
    F_Statistical.BA_Interpretation.BenchmarkIntpData,
    -- Training library
    BinaryTrainLib
  hs-source-dirs: ., _F_Training
  build-depends:
    base >=4.16,
    bytestring,
    containers,
    mtl,
    numeric-tools,
    hasktorch,
    statistics,
    time
  default-language: Haskell2010

executable binary-benchmark
  main-is: BinaryBenchmark.hs
  hs-source-dirs: F_Statistical
  ghc-options: -rtsopts
  build-depends:
    base,
    nesycat-hasktorch,
    mtl,
    containers,
    hasktorch,
    time
  default-language: Haskell2010

executable binary-test-real
  main-is: BinaryTrain.hs
  other-modules: BinaryTrainLib
  hs-source-dirs: _F_Training
  ghc-options: -rtsopts
  build-depends:
    base,
    nesycat-hasktorch,
    mtl,
    containers,
    hasktorch,
    time
  default-language: Haskell2010

executable binary-test-real-beta
  main-is: BinaryTrainBeta.hs
  other-modules: BinaryTrainLib
  hs-source-dirs: _F_Training
  ghc-options: -rtsopts
  build-depends:
    base,
    nesycat-hasktorch,
    mtl,
    containers,
    hasktorch,
    time,
    statistics
  default-language: Haskell2010

